name: Java CI (build & run Weather CLI)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      city:
        description: "City to fetch"
        required: true
        default: "Toronto"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compile
        run: |
          rm -rf out && mkdir -p out
          javac -d out $(find src -name "*.java")

      - name: Run sample
  run: |
    java -cp out com.umair.weathercli.App "${{ github.event.inputs.city }}" | tee weather.txt

- name: Upload result
  uses: actions/upload-artifact@v4
  with:
    name: weather-output
    path: weather.txt

